/**
 * Radio.garden places database metadata
 *
 * Auto-generated by compile_places.py
 * Do not edit manually!
 */

#ifndef PLACES_INFO_H
#define PLACES_INFO_H

#include <stdint.h>

// Database info
#define PLACES_DB_MAGIC     "RGPL"
#define PLACES_DB_VERSION   1
#define PLACES_COUNT        12486
#define PLACES_STRUCT_SIZE  52
#define PLACES_HEADER_SIZE  16

// Place structure (packed, 52 bytes)
typedef struct __attribute__((packed)) {
    char id[16];        // Radio.garden place ID
    int16_t lat_x100;   // Latitude * 100
    int16_t lon_x100;   // Longitude * 100
    char name[28];      // City name (UTF-8, null-terminated)
    char country[4];    // Country code
} Place;

// Verify struct packing
static_assert(sizeof(Place) == PLACES_STRUCT_SIZE, "Place struct size mismatch");

#endif // PLACES_INFO_H
